### ISSUE TITLE
Issue with new Save Tab Group

### ISSUE THREAD

**Issue by theaschn** [samihaddad/vertical-tabs-chrome-extension#37] opened 2024-01-25 01:11 UTC
When the new Save Tab Group added in v120 is activated on a tab group, both tabs and tab groups cannot be selected or expanded from the extension / sidebar. Tabs still work as expected when not in a Saved Tab Group, but not when the new feature is active.

Hope that helps, thanks for the extension!

**Comment by eirikurelisson** [comment] 2024-03-12 09:32
![image](https://github.com/samihaddad/vertical-tabs-chrome-extension/assets/145348689/b73306f0-ff06-4d0d-8808-d65c17f2078a)

I have the same issue! would be nice to have it fixed. Workaround I found was to uncheck the "save group" while using it and re enable before switching to my other computer (to sync the groups)

**Comment by merrickw** [comment] 2024-03-20 14:04
> ![image](https://private-user-images.githubusercontent.com/145348689/312018017-b73306f0-ff06-4d0d-8808-d65c17f2078a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5NDM2NTIsIm5iZiI6MTcxMDk0MzM1MiwicGF0aCI6Ii8xNDUzNDg2ODkvMzEyMDE4MDE3LWI3MzMwNmYwLWZmMDYtNGQwZC04ODA4LWQ2NWMxN2YyMDc4YS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMzIwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDMyMFQxNDAyMzJaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yMWQ4ODZlNjdhYTBlOTUxYWM3NDlhOTk1MmZmMzQyZTRkN2ExODY2YzkxN2I3MDA4ZDg5NzFlMzE5YTU0ZmJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.LCqOCqUdbfLD9yaa8tHg9lCaI1Xavg-CkbSnKGJwxkk)
> 
> I have the same issue! would be nice to have it fixed. Workaround I found was to uncheck the "save group" while using it and re enable before switching to my other computer (to sync the groups)

This workaround works!  Thank you.  
Turning off "Save Group" allows me to click on tabs in this extension.  
When "Save Group" is on, the tabs are listed, but don't respond to clicks.

**Comment by samihaddad** [comment] 2024-03-20 14:21
This issue is caused by Chrome not allowing updates to saved groups, it is currently being worked on from their side. For more details you can follow the issue here: https://issues.chromium.org/issues/323982812

**Comment by samihaddad** [comment] 2024-03-20 14:42
After testing this now it seems to have been fixed with latest Chrome release 123.0.6312.59.

**Comment by samihaddad** [comment] 2024-03-20 16:12
@merrickw this seems to be the most requested feature and also unfortunately a Chrome limitation #42

**Comment by samihaddad** [comment] 2024-03-20 16:13
Closing this issue

**Closed by samihaddad** 2024-03-20 16:13 UTC
Labels: chrome-bug
