### ISSUE TITLE
Unable to collapse groups

### ISSUE THREAD

**Issue by FridgeWheeL** [samihaddad/vertical-tabs-chrome-extension#50] opened 2024-04-17 01:32 UTC
I am unable to collapse the groups in Chrome Version 124.0.6367.61 (Official Build) (64-bit)

**Comment by samihaddad** [comment] 2024-04-17 10:10
This is caused by lack of Chrome support. It will be fixed in next version 125.

**Comment by samihaddad** [comment] 2024-05-16 12:32
Should be fixed with the update.

**Closed by samihaddad** 2024-05-16 12:32 UTC
